//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCL.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeTransaction
    {
        public int ChequeId { get; set; }
        public Nullable<int> LoanId { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<int> BankId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<bool> PaidCash { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentType { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> RecievingBank { get; set; }
    }
}
