//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCL.Core.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FCLDataEntities : DbContext
    {
        public FCLDataEntities()
            : base("name=FCLDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Guarantor> Guarantors { get; set; }
        public virtual DbSet<ChequeTransaction> ChequeTransactions { get; set; }
        public virtual DbSet<LoanTransaction> LoanTransactions { get; set; }
        public virtual DbSet<Duration> Durations { get; set; }
        public virtual DbSet<LoanPaymentType> LoanPaymentTypes { get; set; }
        public virtual DbSet<LoanStatu> LoanStatus { get; set; }
        public virtual DbSet<FCLBranch> FCLBranches { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DSE> DSEs { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
