//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCL.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guarantor
    {
        public int GuarantorId { get; set; }
        public Nullable<int> LoanId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string NameOnCheque { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<int> Bank { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
