//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCL.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string EmployerName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ClientId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<bool> CanCreate { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> DseId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
